<!--Autori: xmarek69, xgajdo24, xbilyd01 -->
<!DOCTYPE html>
<html lang="cs">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta http-equiv="content-type" content="text/html;" charset="ISO-8859-2"/>
    
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <link rel="stylesheet" type="text/css" href="css/sklad.css">
    <link rel="stylesheet" type="text/css" href="css/prijem.css">
    <link rel="stylesheet" type="text/css" href="css/vydej.css">
    <link rel="stylesheet" type="text/css" href="css/historie.css">
    <link rel="stylesheet" type="text/css" href="css/nastaveni.css">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Inventory manager</title>
</head>
<body>
    <header>

    </header>
        <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
    <footer>
        
    </footer>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>